### ISSUE TITLE
Not Working on Anki 2.1.49 Windows 11

### ISSUE THREAD

**Issue by OthmanA-K** [mankinence/ImageResizer#27]
Hi I have tried multiple times to get this addon to work by disabling, deleting and reinstalling but have had no success. When hovering over an image, there is no option to drag to resize. Tried with multiple images.

As stated in the title, I am on Windows 11 and Anki version 2.1.49.

Please help with fixing my issue as soon as possible.

Thank you very much.

**Comment by searene** [comment]
Hi,

That's normal if you don't see the resize options when hovering over an
image because that's not how the addon works. After you install the addon,
your images are automatically resized when pasting or dragged from
other places. If you want to configure the width or height of the resized
image, you can click on "Tools -> Image Resizer" in the menu bar to set
them.

Regards,
Joey
